version: "3"

services:

  cubadb:
    image: 'postgres:14.0-alpine'
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - "./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh"
    ports: 
      - "5432:5432"